from typing import List, Dict, Any
import random

import torch
import re


def extract_computational_steps(reasoning_path: str):
    if reasoning_path.startswith('####'):
        return reasoning_path[4:].strip()

    pattern = r'<<(.*?)>>'
    match = re.findall(pattern, reasoning_path)
    if len(match) == 0:
        return None
    return f'<<{match[0]}>>'


def pre_process_gsm8k(
        instance,
        tokenizer,
        assistant_tokenizer,
        num_thought_tokens=2,
        device=None,
        add_bot_eot=True,
        split='train',
        base_backbone='llama',
        base_special_token=['<|end_of_text|>', '<|reserved_special_token_0|>', '<|reserved_special_token_1|>'],
        assistant_backbone='llama',
        assistant_special_token=['<|end_of_text|>', '<|reserved_special_token_0|>', '<|reserved_special_token_1|>'],
        max_len=-1,
        **kwargs,
):
    base_unk_token, base_bot_token, base_eot_token = base_special_token
    base_bot_token = base_bot_token if add_bot_eot else ''
    base_eot_token = base_eot_token if add_bot_eot else ''

    assistant_unk_token, assistant_bot_token, assistant_eot_token = assistant_special_token
    ques_sample = instance['instance_samples']['match_sample']['question']
    reasoning_list = instance['answer'].split('\n')
    answer = reasoning_list[-1]
    assert answer.startswith('####')
    answer = answer.replace(',', '')
    if '.' in answer:
        answer = float(answer[4:])
    else:
        answer = int(answer[4:])
    question = instance['question']

    thought_tokens = base_unk_token * num_thought_tokens
    soft_thoughts = f'{base_bot_token}{thought_tokens}{base_eot_token}'

    input_template = (f'Solve the following math problem efficiently and clearly:\n'
                      f'- For simple problems (2 steps or fewer):\nProvide a concise solution with minimal equation.\n'
                      f'- For complex problems (3 steps or more):\n'
                      f'Use this step-by-step format:\n\n'
                      f'## Step 1: [Brief calculations]\n'
                      f'## Step 2: [Brief calculations]\n'
                      f'...\n'
                      f'Regardless of the approach, always conclude with:\n'
                      f'Therefore, the final answer is: $\\boxed{{answer}}$. I hope it is correct.\n'
                      f'Where [answer] is just the final number or expression that solves the problem.\n\n'
                      f'Problem: {question}')

    if base_backbone in ['qwen3'] and split in ['train', 'dev']:
        input_template = f'Problem: {question}'

    input_content = f'{input_template}\n\n'
    if num_thought_tokens > 0:
        if base_backbone not in ['qwen3'] or split not in ['train', 'dev']:
            added_content = (f'There are some prompts generated by a weaker assistant model. Some prompts maybe useful '
                             f'while others maybe unuseful for your reasoning. '
                             f'If the prompts are correct, you can use it as reference. '
                             f'If the prompts are not correct, '
                             f'you can ignore them and focus back to solving the problem.\n'
                             f'Here are prompts: {soft_thoughts}')
        else:
            added_content = (f''
                             f'Here are prompts from assistant model for reference: {soft_thoughts}')
        input_content += added_content

    target_content = ''
    if base_backbone in ['qwen3']:
        target_content = '\n\n'

    cot_template = ''
    if split in ['train', 'dev']:
        for idx in range(len(reasoning_list)):
            if base_backbone in ['qwen3']:
                text = re.sub(r" <<.*?>>", "", reasoning_list[idx])
                text = text.replace("** ", "")
                text = text.replace("#### ", "")
                cot_template += f'## Step {idx + 1}: {text}\n'
            else:
                cot_template += f'## Step {idx + 1}: {reasoning_list[idx]}\n'

        cot_template += f'Therefore, the final answer is: $\\boxed{{{answer}}}$.'

    target_content += cot_template

    input_messages = [
        {
            'role': 'user',
            'content': input_content,
        },
    ]
    target_messages = [
        {
            'role': 'user',
            'content': input_content,
        },
        {
            'role': 'assistant',
            'content': target_content,
        },
    ]

    if base_backbone in ['llama', 'qwen']:
        if split in ['train', 'dev']:
            input_ids = tokenizer.apply_chat_template(target_messages)[: max_len]
            pure_input_length = len(tokenizer.apply_chat_template(input_messages))
        else:
            input_ids = tokenizer.apply_chat_template(input_messages)
            pure_input_length = len(input_ids)
    elif base_backbone in ['qwen3']:
        if split in ['train', 'dev']:
            input_ids = tokenizer.apply_chat_template(
                target_messages,
                add_generation_prompt=False,
                enable_thinking=False
            )
            if max_len > 0:
                input_ids = input_ids[: max_len]
            pure_input_ids = tokenizer.apply_chat_template(
                input_messages,
                add_generation_prompt=False,
                enable_thinking=False
            )
            pure_input_length = len(pure_input_ids)
        else:
            input_ids = tokenizer.apply_chat_template(
                input_messages,
                add_generation_prompt=True,
                enable_thinking=False
            )
            pure_input_ids = tokenizer.apply_chat_template(
                input_messages,
                add_generation_prompt=False,
                enable_thinking=False
            )
            pure_input_length = len(pure_input_ids)
    else:
        raise NotImplementedError

    attention_mask = [1] * len(input_ids)

    if assistant_backbone in ['llama']:
        assistant_template = (
            f'You are required to generate {num_thought_tokens} tokens to help another language model '
            f'to solve the following math reasoning task efficiently and clearly. '
            f'Here are the requirements of your generated tokens:\n'
            f'- The tokens should include some useful information for the reasoning problem, '
            f'for example, the numbers and the operations needed for calculation.\n'
            f'- Generate the tokens starts from the most important or the highest related tokens.\n'
            f'- **Informative tokens are required**: (1) Do not need to generate a sentence or paragraph, '
            f'(2) Do not need to generate the uninformative tokens such as serial number.\n'
            f'- The tokens should be useful for large language model to answer the question with the numbers.\n'
            f'...\n\n'
        )

    elif assistant_backbone in ['qwen', 'qwen3']:
        assistant_template = (
            f'You are required to generate {num_thought_tokens} tokens to help another language model '
            f'to solve the following math reasoning task efficiently and clearly. '
            f'Here are the requirements of your generated tokens:\n'
            f'- The tokens should include some useful information for the reasoning problem, '
            f'for example, the numbers and the operations needed for calculation.\n'
            f'- Generate the tokens starts from the most important or the highest related tokens.\n'
            f'- **Informative tokens are required**: (1) Do not need to generate a sentence or paragraph, '
            f'(2) Do not need to generate the uninformative tokens such as serial number.\n'
            f'- The tokens should be useful for large language model to answer the question with the numbers.\n'
            f'- The other language model is good enough to understand the problem, so what you need to do is '
            f'generate some informative key tokens that summarize the problem.\n'
            f'...\n\n'
        )

    else:
        raise NotImplementedError

    assistant_messages = []

    # 生成主问题的assistant message (第0个分支)
    assistant_messages.append([
        {
            'role': 'user',
            'content': f'{assistant_template}'
                       f'Here is the problem: {instance["question"]}.',
        },
        {
            'role': 'assistant',
            'content': f'Here are {num_thought_tokens} tokens to help the language model solve this math reasoning task: '
                       f'{assistant_unk_token * num_thought_tokens}',
        }
    ])
    # 生成每个推理步骤的assistant message
    # for reasoning_list_i in range(len_r):

    assistant_messages.append(
        [
            {
                'role': 'user',
                'content': f'{assistant_template}'
                           f'Here is the problem: {ques_sample}.',
            },
            {
                'role': 'assistant',
                'content': f'Here are {num_thought_tokens} tokens to help the language model solve this math reasoning task: '
                           f'{assistant_unk_token * num_thought_tokens}',
            }
        ]
    )
    # 分支总数 = 1(主问题) + len_r(推理步骤)
    n_assist = len(assistant_messages)
    # 对齐分支token数，前面补主分支的token数
    # per_branch_token_nums = [per_branch_token_nums[0]] + per_branch_token_nums

    # ======================================
    # 【修改点1】核心修改：assistant_ids 改为二维List
    # ======================================
    assistant_ids = []
    for msg in assistant_messages:
        single_assist_ids = assistant_tokenizer.apply_chat_template(msg)
        assistant_ids.append(single_assist_ids)

    # ======================================
    # 【修改点2】核心修改：assistant_attention_mask 改为二维List，与assistant_ids一一对应
    # ======================================
    assistant_attention_mask = []
    for ids in assistant_ids:
        single_attention_mask = [1] * len(ids)
        assistant_attention_mask.append(single_attention_mask)

    # ======================================
    # 【核心大改 ✅】为每个assistant分支生成独立的thought_index，适配各自的token数
    # 格式：thought_index_list = [ [input_s, input_e, assist_s, assist_e], ... ] 长度等于n_assist
    # ======================================
    thought_index_list = []
    # 基础的input侧起止索引（全局不变，所有分支共用）
    base_input_thought_start_idx = pure_input_length - 1 - num_thought_tokens
    if add_bot_eot:
        base_input_thought_start_idx -= 1
    if base_backbone in ['qwen', 'qwen3']:
        base_input_thought_start_idx -= 1
    base_input_thought_end_idx = base_input_thought_start_idx + num_thought_tokens

    # 遍历每个分支，计算独立的assist_thought_s/assist_thought_e
    for assist_idx in range(n_assist):

        cur_assist_ids_len = len(assistant_ids[assist_idx])

        # 计算当前分支的assistant侧起止索引
        cur_assist_thought_start_idx = cur_assist_ids_len - 1 - num_thought_tokens
        if assistant_backbone in ['qwen', 'qwen3']:
            cur_assist_thought_start_idx -= 1
        cur_assist_thought_end_idx = cur_assist_thought_start_idx + num_thought_tokens
        # 每个分支的索引格式：[input_s, input_e, assist_s, assist_e]
        thought_index_list.append([
            base_input_thought_start_idx,
            base_input_thought_end_idx,
            cur_assist_thought_start_idx,
            cur_assist_thought_end_idx
        ])

    if split in ['train']:
        labels = [-100] * (base_input_thought_end_idx + 2) + input_ids[base_input_thought_end_idx + 2:]
    elif split in ['dev']:
        labels = [-100] * len(input_ids)
        labels[-5:] = input_ids[-5:]
    else:
        labels = [-100] * len(input_ids)

    inputs = {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'assistant_input_ids': assistant_ids,  # 二维List [n_assist, seq_len]
        'assistant_attention_mask': assistant_attention_mask,  # 二维List [n_assist, seq_len]
        'labels': labels,
        'thought_index': thought_index_list,  # 二维List [n_assist,4] 核心修改！每个分支独立索引
        # 'per_branch_token_nums': per_branch_token_nums,  # 新增：保存每个分支的token数，模型端可用
    }
    if split in ['train', 'dev']:
        inputs['answer'] = answer

    # ======================================
    # 【修改点3】张量转换适配：所有二维List转三维tensor，完美对齐模型输入
    # ======================================
    # print(device)
    if device is not None:
        input_max_length = max([len(item) for item in [input_ids]])
        # 计算assistant的双层最大长度：n_assist(每个样本的assist条数) + assist_seq_len(单条assist的token长度)
        assistant_n_max = max([len(ids_list) for ids_list in [assistant_ids]])
        assistant_seq_max = max([len(ids) for ids_list in [assistant_ids] for ids in ids_list])
        # 计算thought_index和token数的最大长度
        thought_idx_max_len = 4  # 固定4列
        # token_num_max_len = assistant_n_max

        # 基础模型字段padding（原有逻辑不变）
        input_ids = [(ids + [0] * input_max_length)[:input_max_length] for ids in [input_ids]]
        attention_masks = [(am + [0] * input_max_length)[:input_max_length] for am in [attention_mask]]
        labels = [(label + [-100] * input_max_length)[:input_max_length] for label in [labels]]

        # ======================================
        # 二维List的assistant_input_ids padding逻辑
        # ======================================
        padded_assist_ids = []
        for per_batch_assist_ids in [assistant_ids]:
            padded_single = []
            for ids in per_batch_assist_ids:
                pad_ids = (ids + [0] * assistant_seq_max)[:assistant_seq_max]
                padded_single.append(pad_ids)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * assistant_seq_max for _ in range(pad_n)]
            padded_assist_ids.append(padded_single)

        # ======================================
        # 二维List的assistant_attention_mask padding逻辑，与ids一一对应
        # ======================================
        padded_assist_mask = []
        for per_batch_assist_mask in [assistant_attention_mask]:
            padded_single = []
            for mask in per_batch_assist_mask:
                pad_mask = (mask + [0] * assistant_seq_max)[:assistant_seq_max]
                padded_single.append(pad_mask)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * assistant_seq_max for _ in range(pad_n)]
            padded_assist_mask.append(padded_single)

        # ======================================
        # 【新增】二维List的thought_index padding逻辑 [n_assist,4]
        # ======================================
        padded_thought_index = []
        for per_batch_ti in [thought_index_list]:
            padded_single = []
            for ti in per_batch_ti:
                padded_ti = ti + [0] * (thought_idx_max_len - len(ti)) if len(ti) < 4 else ti[:4]
                padded_single.append(padded_ti)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * thought_idx_max_len for _ in range(pad_n)]
            padded_thought_index.append(padded_single)
        # print(1)
        return {
            'input_ids': torch.tensor(input_ids).long().to(device),  # [batch, input_max_len]
            'attention_mask': torch.tensor(attention_masks).long().to(device),  # [batch, input_max_len]
            'labels': torch.tensor(labels).long().to(device),  # [batch, input_max_len]
            'thought_index': torch.tensor(padded_thought_index).long().to(device),  # ✅【核心】[batch, n_assist, 4]
            'assistant_input_ids': torch.tensor(padded_assist_ids).long().to(device),  # ✅ [batch, n_assist, seq_len]
            'assistant_attention_mask': torch.tensor(padded_assist_mask).long().to(device),
            # ✅ [batch, n_assist, seq_len]
            # 'per_branch_token_nums': torch.tensor(padded_token_nums).long(),  # [batch, n_assist]
        }
    # print(0)
    return inputs

def pre_process_strategy_qa(
    instance,
    tokenizer,
    assistant_tokenizer,
    num_thought_tokens=2,
    device=None,
    add_bot_eot=True,
    split='train',
    base_backbone='llama',
    base_special_token=['<|end_of_text|>', '<|reserved_special_token_0|>', '<|reserved_special_token_1|>'],
    assistant_backbone='llama',
    assistant_special_token=['<|end_of_text|>', '<|reserved_special_token_0|>', '<|reserved_special_token_1|>'],
    **kwargs,
):
    base_unk_token, base_bot_token, base_eot_token = base_special_token
    base_bot_token = base_bot_token if add_bot_eot else ''
    base_eot_token = base_eot_token if add_bot_eot else ''

    assistant_unk_token, assistant_bot_token, assistant_eot_token = assistant_special_token
    ques_sample = instance['instance_samples']['match_sample']['question']

    answer = 'Yes' if instance['answer'] else 'No'
    reasoning_list = instance['facts']

    thought_tokens = base_unk_token * num_thought_tokens
    soft_thoughts = f'{base_bot_token}{thought_tokens}{base_eot_token}'

    input_content = f'You are required to answer the following question with `Yes` or `No`: {instance["question"]}\n\n'
    if num_thought_tokens > 0:
        input_content += f'Here are something useful for your reasoning: {soft_thoughts}\n\n'
    input_content += f'Therefore, the final answer is `Yes` or `No`?'

    if base_backbone in ['qwen3']:
        target_content = '<think>\n\n</think>'
    else:
        target_content = ''

    if split in ['train', 'dev']:
        target_content += (f'OK. The question is {instance["question"]}\n\n'
                           f'Now let\'s start reasoning according to the following facts:\n')
    else:
        target_content += ''

    cot_template = ''
    if split in ['train', 'dev']:
        for idx in range(len(reasoning_list)):
            cot_template += f'## Step {idx + 1}: {reasoning_list[idx]}\n'
        cot_template += f'Finished reasoning, the answer is: {answer}.'

    target_content += cot_template

    input_messages = [
        {
            'role': 'user',
            'content': input_content,
        },
    ]
    target_messages = [
        {
            'role': 'user',
            'content': input_content,
        },
        {
            'role': 'assistant',
            'content': target_content,
        },
    ]
    code_messages = [
        {
            'role': 'feature extractor',
            'content': f'Extract the core mathematical feature of this word problem, retain only the key logical structure and arithmetic relationship of the problem, ignore the specific scenario description and specific numbers, for the purpose of clustering similar mathematical problems.'
                       f'Problem: {instance["question"]}',
        },
    ]
    if base_backbone in ['llama', 'qwen']:
        if split in ['train', 'dev']:
            input_ids = tokenizer.apply_chat_template(target_messages)
            pure_input_length = len(tokenizer.apply_chat_template(input_messages))
            code_ids = tokenizer.apply_chat_template(code_messages)

        else:
            input_ids = tokenizer.apply_chat_template(input_messages)
            pure_input_length = len(input_ids)
            code_ids = tokenizer.apply_chat_template(code_messages)

    elif base_backbone in ['qwen3']:
        if split in ['train', 'dev']:
            input_ids = tokenizer.apply_chat_template(
                target_messages,
                add_generation_prompt=False,
                enable_thinking=False
            )
            pure_input_ids = tokenizer.apply_chat_template(
                input_messages,
                add_generation_prompt=False,
                enable_thinking=False
            )
            pure_input_length = len(pure_input_ids)
        else:
            input_ids = tokenizer.apply_chat_template(
                input_messages,
                add_generation_prompt=True,
                enable_thinking=False,
            )
            pure_input_ids = tokenizer.apply_chat_template(
                input_messages,
                add_generation_prompt=False,
                enable_thinking=False
            )
            pure_input_length = len(pure_input_ids)
    else:
        raise NotImplementedError

    attention_mask = [1] * len(input_ids)

    assistant_template = (f'You are required to generate {num_thought_tokens} tokens to help another language model '
                          f'to solve the following strategy reasoning task efficiently and clearly:\n'
                          f'- The tokens should include some useful information for the reasoning problem.\n'
                          f'- Generate the tokens starts from the most important or the highest related tokens.\n'
                          f'- **Informative tokens are required**: (1) Do not need to generate a sentence or paragraph, '
                          f'(2) Do not need to generate the uninformative tokens such as serial number.\n'
                          f'- The tokens should be useful for large language model to answer the question with '
                          f'`Yes` or `No`.\n'
                          f'...\n\n'
                          f'Here is the problem: {instance["question"]}')


    assistant_messages = []

    # 生成主问题的assistant message (第0个分支)
    assistant_messages.append([
        {
            'role': 'user',
            'content': f'{assistant_template}'
                       f'Here is the problem: {instance["question"]}.',
        },
        {
            'role': 'assistant',
            'content': f'Here are {num_thought_tokens} tokens to help the language model solve this strategy reasoning task: '
                       f'{assistant_unk_token * num_thought_tokens}',
        }
    ])
    # 生成每个推理步骤的assistant message
    # for reasoning_list_i in range(len_r):

    assistant_messages.append(
        [
            {
                'role': 'user',
                'content': f'{assistant_template}'
                           f'Here is the problem: {ques_sample}.',
            },
            {
                'role': 'assistant',
                'content': f'Here are {num_thought_tokens} tokens to help the language model solve this math reasoning task: '
                           f'{assistant_unk_token * num_thought_tokens}',
            }
        ]
    )
    # 分支总数 = 1(主问题) + len_r(推理步骤)
    n_assist = len(assistant_messages)
    # 对齐分支token数，前面补主分支的token数
    # per_branch_token_nums = [per_branch_token_nums[0]] + per_branch_token_nums

    # ======================================
    # 【修改点1】核心修改：assistant_ids 改为二维List
    # ======================================
    assistant_ids = []
    for msg in assistant_messages:
        single_assist_ids = assistant_tokenizer.apply_chat_template(msg)
        assistant_ids.append(single_assist_ids)

    # ======================================
    # 【修改点2】核心修改：assistant_attention_mask 改为二维List，与assistant_ids一一对应
    # ======================================
    assistant_attention_mask = []
    for ids in assistant_ids:
        single_attention_mask = [1] * len(ids)
        assistant_attention_mask.append(single_attention_mask)

    # ======================================
    # 【核心大改 ✅】为每个assistant分支生成独立的thought_index，适配各自的token数
    # 格式：thought_index_list = [ [input_s, input_e, assist_s, assist_e], ... ] 长度等于n_assist
    # ======================================
    thought_index_list = []
    # 基础的input侧起止索引（全局不变，所有分支共用）
    base_input_thought_start_idx = pure_input_length - 1 - num_thought_tokens
    if add_bot_eot:
        base_input_thought_start_idx -= 1
    if base_backbone in ['qwen', 'qwen3']:
        base_input_thought_start_idx -= 1
    base_input_thought_end_idx = base_input_thought_start_idx + num_thought_tokens

    # 遍历每个分支，计算独立的assist_thought_s/assist_thought_e
    for assist_idx in range(n_assist):

        cur_assist_ids_len = len(assistant_ids[assist_idx])

        # 计算当前分支的assistant侧起止索引
        cur_assist_thought_start_idx = cur_assist_ids_len - 1 - num_thought_tokens
        if assistant_backbone in ['qwen', 'qwen3']:
            cur_assist_thought_start_idx -= 1
        cur_assist_thought_end_idx = cur_assist_thought_start_idx + num_thought_tokens
        # 每个分支的索引格式：[input_s, input_e, assist_s, assist_e]
        thought_index_list.append([
            base_input_thought_start_idx,
            base_input_thought_end_idx,
            cur_assist_thought_start_idx,
            cur_assist_thought_end_idx
        ])


    if split in ['train']:
        labels = [-100] * pure_input_length + input_ids[pure_input_length:]
    elif split in ['dev']:
        labels = [-100] * len(input_ids)
        labels[-3] = input_ids[-3]
    else:
        labels = [-100] * len(input_ids)

    inputs = {
        'input_ids': input_ids,

        'attention_mask': attention_mask,
        'assistant_input_ids': assistant_ids,
        'assistant_attention_mask': assistant_attention_mask,
        'labels': labels,
        'thought_index': thought_index_list,
    }
    if split in ['train', 'dev']:
        inputs['answer'] = answer

    if device is not None:
        input_max_length = max([len(item) for item in [input_ids]])
        # 计算assistant的双层最大长度：n_assist(每个样本的assist条数) + assist_seq_len(单条assist的token长度)
        assistant_n_max = max([len(ids_list) for ids_list in [assistant_ids]])
        assistant_seq_max = max([len(ids) for ids_list in [assistant_ids] for ids in ids_list])
        # 计算thought_index和token数的最大长度
        thought_idx_max_len = 4  # 固定4列
        # token_num_max_len = assistant_n_max

        # 基础模型字段padding（原有逻辑不变）
        input_ids = [(ids + [0] * input_max_length)[:input_max_length] for ids in [input_ids]]
        attention_masks = [(am + [0] * input_max_length)[:input_max_length] for am in [attention_mask]]
        labels = [(label + [-100] * input_max_length)[:input_max_length] for label in [labels]]

        # ======================================
        # 二维List的assistant_input_ids padding逻辑
        # ======================================
        padded_assist_ids = []
        for per_batch_assist_ids in [assistant_ids]:
            padded_single = []
            for ids in per_batch_assist_ids:
                pad_ids = (ids + [0] * assistant_seq_max)[:assistant_seq_max]
                padded_single.append(pad_ids)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * assistant_seq_max for _ in range(pad_n)]
            padded_assist_ids.append(padded_single)

        # ======================================
        # 二维List的assistant_attention_mask padding逻辑，与ids一一对应
        # ======================================
        padded_assist_mask = []
        for per_batch_assist_mask in [assistant_attention_mask]:
            padded_single = []
            for mask in per_batch_assist_mask:
                pad_mask = (mask + [0] * assistant_seq_max)[:assistant_seq_max]
                padded_single.append(pad_mask)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * assistant_seq_max for _ in range(pad_n)]
            padded_assist_mask.append(padded_single)

        # ======================================
        # 【新增】二维List的thought_index padding逻辑 [n_assist,4]
        # ======================================
        padded_thought_index = []
        for per_batch_ti in [thought_index_list]:
            padded_single = []
            for ti in per_batch_ti:
                padded_ti = ti + [0] * (thought_idx_max_len - len(ti)) if len(ti) < 4 else ti[:4]
                padded_single.append(padded_ti)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * thought_idx_max_len for _ in range(pad_n)]
            padded_thought_index.append(padded_single)

        return {
            'input_ids': torch.tensor(input_ids).long().to(device),  # [batch, input_max_len]
            'attention_mask': torch.tensor(attention_masks).long().to(device),  # [batch, input_max_len]
            'labels': torch.tensor(labels).long().to(device),  # [batch, input_max_len]
            'thought_index': torch.tensor(padded_thought_index).long().to(device),  # ✅【核心】[batch, n_assist, 4]
            'assistant_input_ids': torch.tensor(padded_assist_ids).long().to(device),  # ✅ [batch, n_assist, seq_len]
            'assistant_attention_mask': torch.tensor(padded_assist_mask).long().to(device),
            # ✅ [batch, n_assist, seq_len]
            # 'per_branch_token_nums': torch.tensor(padded_token_nums).long(),  # [batch, n_assist]
        }

    return inputs

class CustomDataCollator:

    def __call__(self, batch: List[Dict[str, Any]]) -> Dict[str, torch.Tensor]:
        input_ids = [item['input_ids'] for item in batch]
        attention_masks = [item['attention_mask'] for item in batch]
        labels = [item['labels'] for item in batch]
        thought_index = [item['thought_index'] for item in batch]  # 每个元素是二维List [n_assist,4]
        assistant_input_ids = [item['assistant_input_ids'] for item in batch]  # 每个元素是二维List [n_assist, seq_len]
        assistant_attention_mask = [item['assistant_attention_mask'] for item in
                                    batch]  # 每个元素是二维List [n_assist, seq_len]
        # per_branch_token_nums = [item.get('per_branch_token_nums', []) for item in batch]  # 每个分支的token数

        input_max_length = max([len(item) for item in input_ids])
        # 计算assistant的双层最大长度：n_assist(每个样本的assist条数) + assist_seq_len(单条assist的token长度)
        assistant_n_max = max([len(ids_list) for ids_list in assistant_input_ids])
        assistant_seq_max = max([len(ids) for ids_list in assistant_input_ids for ids in ids_list])
        # 计算thought_index和token数的最大长度
        thought_idx_max_len = 4  # 固定4列
        # token_num_max_len = assistant_n_max

        # 基础模型字段padding（原有逻辑不变）
        input_ids = [(ids + [0] * input_max_length)[:input_max_length] for ids in input_ids]
        attention_masks = [(am + [0] * input_max_length)[:input_max_length] for am in attention_masks]
        labels = [(label + [-100] * input_max_length)[:input_max_length] for label in labels]

        # ======================================
        # 二维List的assistant_input_ids padding逻辑
        # ======================================
        padded_assist_ids = []
        for per_batch_assist_ids in assistant_input_ids:
            padded_single = []
            for ids in per_batch_assist_ids:
                pad_ids = (ids + [0] * assistant_seq_max)[:assistant_seq_max]
                padded_single.append(pad_ids)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * assistant_seq_max for _ in range(pad_n)]
            padded_assist_ids.append(padded_single)

        # ======================================
        # 二维List的assistant_attention_mask padding逻辑，与ids一一对应
        # ======================================
        padded_assist_mask = []
        for per_batch_assist_mask in assistant_attention_mask:
            padded_single = []
            for mask in per_batch_assist_mask:
                pad_mask = (mask + [0] * assistant_seq_max)[:assistant_seq_max]
                padded_single.append(pad_mask)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * assistant_seq_max for _ in range(pad_n)]
            padded_assist_mask.append(padded_single)

        # ======================================
        # 【新增】二维List的thought_index padding逻辑 [n_assist,4]
        # ======================================
        padded_thought_index = []
        for per_batch_ti in thought_index:
            padded_single = []
            for ti in per_batch_ti:
                padded_ti = ti + [0] * (thought_idx_max_len - len(ti)) if len(ti) < 4 else ti[:4]
                padded_single.append(padded_ti)
            if len(padded_single) < assistant_n_max:
                pad_n = assistant_n_max - len(padded_single)
                padded_single += [[0] * thought_idx_max_len for _ in range(pad_n)]
            padded_thought_index.append(padded_single)

        valid_token_loss = [item['valid_token_loss'] for item in batch]
        valid_token_loss_mean = [item['valid_token_loss_mean'] for item in batch]

        return {
            'input_ids': torch.tensor(input_ids).long(),  # [batch, input_max_len]
            'attention_mask': torch.tensor(attention_masks).long(),  # [batch, input_max_len]
            'labels': torch.tensor(labels).long(),  # [batch, input_max_len]
            'thought_index': torch.tensor(padded_thought_index).long(),  # ✅【核心】[batch, n_assist, 4]
            'assistant_input_ids': torch.tensor(padded_assist_ids).long(),  # ✅ [batch, n_assist, seq_len]
            'assistant_attention_mask': torch.tensor(padded_assist_mask).long(),  # ✅ [batch, n_assist, seq_len]
            'valid_token_loss': torch.tensor(valid_token_loss[0]),
            'valid_token_loss_mean': torch.tensor(valid_token_loss_mean[0])
        }